insert into customer(
        id,
        name,
        email,
        balance,
        rating,
        birth_date,
        married
    )
values (
        'bayu',
        'Bayu',
        'bayu@mail.com',
        1000000,
        90.0,
        '1996-08-12',
        true
    ),
    (
        'aan',
        'Aan',
        'aan@mail.com',
        5000000,
        85.5,
        '1995-11-02',
        true
    ),
    (
        'fuji',
        'Fuji',
        'fuji@mail.com',
        7500000,
        88.5,
        '1997-06-22',
        true
    );